katalon-studio/katalon-studio-basic-report-plugin

Include/resources/test_case_tpl.jrxml
Include/scripts/groovy/com/kms/katalon/core/pdf/ResourceUtil.java
Include/scripts/groovy/com/kms/katalon/core/reporting/XmlStringUtil.java

Fix: [PDF] Cannot export PDF file without image attached

---

Include/resources/test_case_tpl.jrxml
Include/scripts/groovy/com/kms/katalon/core/reporting/XmlStringUtil.java

Fix [PDF] Cannot export PDF report if a test step's message contains any special characters

---

Keywords/katalon-plugin.json
Test Listeners/KatalonReportListener.groovy

Remove auto export JUnit in Settings

---

Include/resources/test_case_tpl.jrxml

Export PDF throws an exception if the content includes an oversize image

---

Include/scripts/groovy/com/kms/katalon/core/reporting/ReportWriterUtil.java

Bring back Info Logs

---

Test Listeners/KatalonReportListener.groovy

Resolve [STUDIO-906](https://katalon.atlassian.net/browse/STUDIO-906)

[Studio 906] - KRE could not generate JUnit report and send report to TestOps

---

Include/scripts/groovy/com/kms/katalon/core/pdf/TestSuitePdfGenerator.java
Include/scripts/groovy/com/kms/katalon/core/reporting/JsSuiteModel.java
Include/scripts/groovy/com/kms/katalon/core/reporting/ReportWriterUtil.java
README.md

Resolve to generate Reports for HTML, PDF and CSV for Test Suite Report 
- function TestSuiteLogRecord.filterFinalTestCasesResult() please prefer this PR [here ](https://github.com/katalon-studio/katalon/pull/5221) for more details.
- After merging this PR, I will generate a build and add file JAR to the PR mentioned above.
---

[STUDIO-995] RIS 2.2 Consolidated Report in HTML, PDF, CSV format

---

Include/resources/test_suite_tpl.jrxml
Include/scripts/groovy/com/kms/katalon/core/reporting/JsSuiteModel.java

CHECKLIST
Resolve [STUDIO-995](https://katalon.atlassian.net/browse/STUDIO-995)
---

[STUDIO-995] Resolve not match final results on HTML and PDF

---

Include/scripts/groovy/com/kms/katalon/core/reporting/JsTestModel.java
Include/scripts/groovy/com/kms/katalon/core/reporting/plugin/KatalonExportReportProvider.java
Include/scripts/groovy/com/kms/katalon/core/reporting/template/html_content.txt
Include/scripts/groovy/com/kms/katalon/core/reporting/template/html_template.txt

CHECKLIST
Resolve [STUDIO-1057](https://katalon.atlassian.net/browse/STUDIO-1057)
---

[STUDIO-1057] Retry Immediately: Add Retried time(s) to HTML Report

---

Include/scripts/groovy/com/kms/katalon/core/reporting/JsSuiteModel.java

STUDIO-1058 fix incorrect number of total skips in html report

---

Test Listeners/KatalonReportListener.groovy

[STUDIO-1001] CTS1.2 CLI option used in TSC run in Sequential Mode

---

Test Listeners/KatalonReportListener.groovy

[STUDIO-1142] Incomplete Test Suite: Turn on generate reports in HTML, PDF, CSV automatically

---

Include/scripts/groovy/com/kms/katalon/core/reporting/JsSuiteModel.java

Code review checklist for [STUDIO-1041](https://katalon.atlassian.net/browse/STUDIO-1041)

[STUDIO-1041] Fix execution's elapsed time is NOT matched between Katalon and Report generated

---

Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/JsTestModel.java
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_content.txt
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_template.txt

KS commit :https://github.com/katalon-studio/katalon/pull/5426

[STUDIO-204] Fix issues of the Data Binding in HTML report feature.

---

Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_template.txt

Fixing 2 errors: STUDIO-1504 & STUDIO-1503.

[STUDIO-1503 & STUDIO-1504]  Fixing skip status is undefined

---

Include/resources/test_suite_tpl.jrxml
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_content.txt

Resolve 
- [STUDIO-1568](https://katalon.atlassian.net/browse/STUDIO-1568) 
- [STUDIO-1570](https://katalon.atlassian.net/browse/STUDIO-1570) 
- [STUDIO-1567](https://katalon.atlassian.net/browse/STUDIO-1567) 
- [STUDIO-1569](https://katalon.atlassian.net/browse/STUDIO-1569)

[STUDIO-979] Resolve Reports for TestCloud Integration

---

Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/JsTestModel.java
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_content.txt
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_template.txt

[STUDIO-1479](https://katalon.atlassian.net/browse/STUDIO-1479)
---

[STUDIO-1479] Add iteration name accordingly to the binding in the Test cases table and HTML report.

---

Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/JsTestModel.java
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_content.txt
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_template.txt

From pull request/ ticket: https://github.com/katalon-studio/katalon/pull/5607

[STUDIO-1768] [SAP] Adjust iteration's name in DDT report 

---

build.gradle

upgrade java 17
gradle from 5.6 to 7.3
jasperreports from 6.2.2 to 6.20.5
com.katalon.gradle-plugin from 0.0.7 to 0.1.1
com.github.johnrengelman.shadow from 4.0.4 to 6.1.0

[STUDIO-3951] Generate PDF report

---

Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/template/html_content.txt
build.gradle

[STUDIO-3595](https://katalon.atlassian.net/browse/STUDIO-3595)
[STUDIO-3595]: https://katalon.atlassian.net/browse/STUDIO-3595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[STUDIO-3595] hide navigate url

---

Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/JsModelProperty.java
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/JsStepModel.java
Include/scripts/groovy/com/kms/katalon/core/reporting/basic/reporting/ReportWriterUtil.java
README.md
Test Listeners/KatalonReportListener.groovy

[STUDIO-4266](https://katalon.atlassian.net/browse/STUDIO-4266)
More info [comment](https://katalon.atlassian.net/browse/STUDIO-4266?focusedCommentId=132256)
[STUDIO-4266]: https://katalon.atlassian.net/browse/STUDIO-4266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[STUDIO-4266] Improve mechanism for generate heavy HTML reports

---

Test Listeners/KatalonReportListener.groovy

[STUDIO-4266](https://katalon.atlassian.net/browse/STUDIO-4266)
[STUDIO-4266]: https://katalon.atlassian.net/browse/STUDIO-4266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

STUDIO-4266]  Hiding FileAlreadyExistsException
